import Carrusel from "./components/Carrusel";
import Header from "./components/Header";
import GlobalProvider from "./context/GlobalContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <main className="lg:px-20 md:px-20 sm:px-14 xs:px-6 xxs:px-5 pt-5">
            <Header />
            {/*<Carrusel />*/}
            {children}
          </main>
        </GlobalProvider>
      </body>
    </html>
  );
}
